AWSTemplateFormatVersion: '2010-09-09'
Description: 'Complete IAM roles for EKS and Jenkins'

Parameters:
  EnvironmentName:
    Description: Environment name that will be prefixed to resource names
    Type: String
    Default: dev

Resources:
  # EKS Cluster Role
  EksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-eks-cluster-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-eks-cluster-role

  # EKS Node Group Role
  EksNodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-eks-nodegroup-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-eks-nodegroup-role

  # Jenkins IAM Role
  JenkinsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-jenkins-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonECR-FullAccess
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-jenkins-role

  # Jenkins Instance Profile
  JenkinsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref JenkinsRole

  # Jenkins IAM Policy
  JenkinsIAMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${EnvironmentName}-jenkins-iam-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:*
              - eks:*
              - ec2:*
              - elasticloadbalancing:*
              - autoscaling:*
              - iam:PassRole
              - s3:*
            Resource: '*'
      Roles:
        - !Ref JenkinsRole

Outputs:
  EksClusterRoleArn:
    Description: EKS Cluster IAM Role ARN
    Value: !GetAtt EksClusterRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EksClusterRoleArn

  EksNodeGroupRoleArn:
    Description: EKS Node Group IAM Role ARN
    Value: !GetAtt EksNodeGroupRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EksNodeGroupRoleArn

  JenkinsRoleArn:
    Description: Jenkins IAM Role ARN
    Value: !GetAtt JenkinsRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-JenkinsRoleArn

  JenkinsInstanceProfileArn:
    Description: Jenkins Instance Profile ARN
    Value: !GetAtt JenkinsInstanceProfile.Arn
    Export:
      Name: !Sub ${EnvironmentName}-JenkinsInstanceProfileArn