AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Cluster Role with Policy'

Resources:
  EksRoleWithPolicy:
    Type: AWS::IAM::Role
    Properties:
      RoleName: eks-role-with-policy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Path: '/'

Outputs:
  EksRoleWithPolicyArn:
    Description: EKS Role with Policy ARN
    Value: !GetAtt EksRoleWithPolicy.Arn