AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Node Group Role with Policies'

Resources:
  EksNodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: eks-nodegroup-role-test
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Path: '/'

Outputs:
  EksNodeGroupRoleArn:
    Description: EKS Node Group Role ARN
    Value: !GetAtt EksNodeGroupRole.Arn