AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple EKS Cluster Role'

Resources:
  SimpleEksRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: simple-eks-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'

Outputs:
  SimpleEksRoleArn:
    Description: Simple EKS Role ARN
    Value: !GetAtt SimpleEksRole.Arn