AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple IAM role test'

Resources:
  TestRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: test-simple-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess