AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step 2 simplified: EKS Cluster Role and simplified Node Group Role'

Parameters:
  EnvironmentName:
    Description: Environment name that will be prefixed to resource names
    Type: String
    Default: dev

Resources:
  # EKS Cluster Role
  EksClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-eks-cluster-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-eks-cluster-role

  # Simplified EKS Node Group Role with only one policy
  EksNodeGroupRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-eks-nodegroup-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-eks-nodegroup-role

Outputs:
  EksClusterRoleArn:
    Description: EKS Cluster IAM Role ARN
    Value: !GetAtt EksClusterRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EksClusterRoleArn

  EksNodeGroupRoleArn:
    Description: EKS Node Group IAM Role ARN
    Value: !GetAtt EksNodeGroupRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EksNodeGroupRoleArn